### ISSUE TITLE
Autosetup not working with mysql

### ISSUE THREAD

**Issue by dhilgarth** [Gronis/docker-seafile#3]
docker-compose file:
```
version: "3.7"
services:
  mysql-seafile:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - internal
    volumes:
      - type: volume
        source: mysqldata-seafile
        target: /var/lib/mysql

  seafile:
    image: gronis/seafile
    restart: always
    networks:
     - web
     - internal
    labels:
     - "traefik.enable=true"
     - "traefik.frontend.rule=Host:cloud.sovarto.com"
     - "traefik.port=8000"
     - "traefik.protocol=http"
     - "traefik.docker.network=web"
    environment:
      SEAFILE_NAME: "Sovarto Cloud"
      SEAFILE_ADDRESS: cloud.sovarto.com
      SEAFILE_ADMIN: info@sovarto.com
      SEAFILE_ADMIN_PW: ${SEAFILE_ADMIN_PASSWORD}
      MYSQL_SERVER: mysql-seafile
      MYSQL_USER: seafile
      MYSQL_USER_PASSWD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWD: ${DB_PASSWORD}
    volumes:
     - type: volume
       source: seafile-data
       target: /seafile
    ports:
      - "8082:8082"
    depends_on:
     - mysql-seafile

volumes:
  mysqldata-seafile:
  seafile-data:
```

When I start it, I get the following output:
```seafile_1        | /tmp/seafile.env: line 2: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
seafile_1        | /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
seafile_1        |
seafile_1        | seafile server not running yet
seafile_1        | Done.
seafile_1        | /tmp/seafile.env: line 2: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
seafile_1        | /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
seafile_1        |
seafile_1        | Error: there is no ccnet config directory.
seafile_1        | Have you run setup-seafile.sh before this?
seafile_1        |
seafile_1        | /tmp/seafile.env: line 2: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
seafile_1        | /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
seafile_1        |
seafile_1        | Error: there is no conf/ directory.
seafile_1        | Have you run setup-seafile.sh before this?
seafile_1        |
seafile_1        | setup_mysql
seafile_1        | 2019/04/28 06:44:54 Waiting for: tcp://mysql-seafile:3306
seafile_1        | 2019/04/28 06:44:54 Connected to tcp://mysql-seafile:3306
```

To make it work, I have to perform the following steps:
1. Set the `MODE` environment variable to `setup_sqlite` - yes, even though I am using MySQL - and `docker-compose up`
2. Set the `MODE` environment variable to `setup_mysql` and `docker-compose up`
3. Remove the `MODE` environment variable and `docker-compose up`
