### ISSUE TITLE
Container never finishes setup, 502 on port 8000

### ISSUE THREAD

**Issue by anLizard** [Gronis/docker-seafile#5]
Navigating to the url seafile is reverse proxied to results in 502. I keep getting this in the logs after `docker-compose up -d`

```
seafile-0            | /tmp/seafile.env: line 2: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
seafile-0            | /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
seafile-0            |
seafile-0            | seafile server not running yet
seafile-0            | Done.
seafile-0            | Fixing gunicorn config.
seafile-0            | sed: can't read /seafile/conf/gunicorn.conf: No such file or directory
seafile-0            | cat: /seafile/version: No such file or directory
seafile-0            | /usr/local/bin/seafile-entrypoint.sh: line 7: 7.0.5: command not found
seafile-0            | /tmp/seafile.env: line 2: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
seafile-0            | /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
seafile-0            |
seafile-0            | Seahub is not running
seafile-0            | Done.
```
  
My docker-compose.yml:

```
version: "3"

networks:
  frontend:
  sf:

services:

  caddy:
    image: lucaslorentz/caddy-docker-proxy:0.3.6
    container_name: caddy-0
    command: -email email@example.com -agree=true -log stdout
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./caddy:/root/.caddy
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
	  
  seafile:
    image: gronis/seafile:latest
    container_name: seafile-0
    networks:
      - frontend
      - sf
    expose:
      # seahub
      - 8000
      # seafhttp
      - 8082
    restart: always
    volumes:
      - ./seafile/data:/seafile:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SEAFILE_NAME=SEafile
      - SEAFILE_ADDRESS=sea.example.org
      - MYSQL_SERVER=seafile-db
      - MYSQL_USER=seafile
      - MYSQL_USER_PASSWORD=SomePassword
      - MYSQL_ROOT_PASSWORD=OtherPassword
      - SEAFILE_ADMIN_EMAIL=some@mail.com
      - SEAFILE_ADMIN_PW=aPassword

    depends_on:
      - seafile-db
    labels:
      - caddy_0.address=sea.example.com
      - caddy_0.targetport=8000
      - caddy_0.proxy.transparent=
      - caddy_1.address=sea.example.com/seafhttp
      - caddy_1.targetport=8082
      - caddy_1.proxy.transparent=
      - caddy_1.proxy.without=/seafhttp
	  
  seafile-db:
    image: mariadb
    container_name: seafile-db
    networks:
      - sf
    restart: always
    volumes:
      - ./seafile/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_LOG_CONSOLE=true
      - MYSQL_ROOT_PASSWORD=OtherPassword
```
