### ISSUE TITLE
Couple of questions to get started

### ISSUE THREAD

**Issue by zilexa** [Gronis/docker-seafile#6]
As a noob running Ubuntu on an Intel based home server with several services running via Docker (Compose), I really want to use Seafile. But I am not sure which docker version to pick.

Yours seems straightforward for a beginner like me, you even provide a full docker-compose.yml example with reverse proxy, SSL and MariaDB! 
Do you recommend MariaDB for speed and stability over SQLite?

[Haiwen's version](https://github.com/haiwen/seafile-docker) includes Memcached. I believe that can greatly speed up Seafile and I have 32GB ECC Ram so it would be of good use. Is your setup capable of using it with Memcached?

**Comment by Gronis** [comment]
Hi! Good choice to try out seafile. 

I have not used SQLite with seafile (other than testing the docker image), so I don't know how the performance compares between the two setups.

Unfortunately, I have not tested it with memcache. But reading the [documentation](https://seafile.readthedocs.io/en/latest/installation/memcached/#configure-seahub), it looks like you only need to add a few lines to `seahub_settings.py` and add a `memcache` service in the docker compose file; So I don't see any problems there.

Personally, I don't have memcache setup because seafile is already fast. If you are using it in a business setup with several users, then memcache might be necessary.

**Comment by zilexa** [comment]
Thanks a lot for that tip. I will try it. I noticed the docker image you use for MySQL doesn't mention MariaDB anywhere but someone did create an issue asking the author to change is readme since it is MariaDB. So I assume it is not MySQL but actually MariaDB.

Can I ask which domain provider you use for the SSL part? I currently use a FreeDNS subdomain (free) without SSL and searched for hours but they do not seem to support SSL.

**Comment by Gronis** [comment]
I did also use syncthing in the past and moved to seafile because I wanted to have version control on my files. I almost had a catastrophic failure with syncthing where one of the clients could not access the file storage, and because the data directory was empty, it "synced" to the other clients and removed everything in that library from all the clients. Fortunately, I was able to restore 98% of my data using normal data recovery programs. I haven't touched syncthing after that incident.

Since MariaDB is pretty much a drop in replacement for MySQL, I don't really think of them as separate. But for correctness, I guess you are right.

Unfortunately, I don't have much info about free domain providers since I use a paid domain. I guess most (paid) domain name provides support ssl. You can get them pretty cheep, like ~12 USD or so per year. I host many things under the same domain name (using subdomains) which make the cost worth it I think.

**Comment by zilexa** [comment]
I had a discussion on the SyncThing forum a few days ago about the fact that if I enable "ignore-deletes", the UI should not show "syncing 98%" constantly even when it is done syncing. They disagreed, since deletes are not synced, it will never be 100%, by design. Also the red "Out Of Sync" message is confusing, leading one to believe the syncing has halted but instead syncing DOES still happen and SyncThing runs fine as expected, by not syncing the deletes. They disagreed again.. then it became clear this is not the solution for me :)

I will find a nice paid provider, set up the domain and try your docker compose. Thanks!

**Comment by zilexa** [comment]
Sorry just one more question as this SSL stuff is new to me. 
Does the domain provider need to be on the Certbot list? 
https://certbot.eff.org/hosting_providers

**Comment by Gronis** [comment]
If you host your own server, then no. I think that is when you buy hosting from someone else. 😃

**Comment by zilexa** [comment]
Sorry for abusing you, but you have been very helpful!
One more question, using your example for SSL support, how can I support for subdomains? 
For example I have mydomain.com and want seafile.mydomain.com and firefoxsync.mydomain.com and in the future perhaps more subdomains. 

The [seperate docker](https://github.com/linuxserver/docker-letsencrypt/blob/master/README.md) for letsencrypt has an env variable for it (SUBDOMAINS=www,seafile,firefoxsync) but I prefer to use your menthod, without that letsencrypt seperate container.

**Comment by Gronis** [comment]
If you are using the setup in README (with nginx, nginx-gen and jrcs/letsencrypt-nginx-proxy-companion) then the latter uses docker to figure out which domains to grab certificates for (using environment variables for that docker container). nginx-gen generates a config for nginx, so that nginx knows which docker container to redirect the client to by looking at the domain header in the request. You only need one `nginx` `nginx-gen` and `jrcs/letsencrypt-nginx-proxy-companion` for all subdomains on your server.

I you are using multiple subdomains on one server, I suggest that you add those three in its own docker-compose and use an external docker network (so that docker containers from different docker-compose file can talk to each other).

If you are using the traefik setup, I'm not sure how to setup multiple subdomains. It was added in a merge request and I do not use that setup personally.

**Comment by Gronis** [comment]
```yaml
version: "2"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    environment:
      TZ: "Europe/Stockholm"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/services/gatekeeper/conf:/etc/nginx/conf.d:ro
      - /data/services/gatekeeper/vhost:/etc/nginx/vhost.d:ro
      - /data/services/gatekeeper/certs:/etc/nginx/certs:ro
      - /data/services/gatekeeper/htpasswd:/etc/nginx/htpasswd:ro
      - /usr/share/nginx/html
    networks:
      - proxy-tier

  nginx-gen:
    image: jwilder/docker-gen:0.7.3
    container_name: nginx-gen
    restart: always
    environment:
      TZ: "Europe/Stockholm"
    depends_on:
      - nginx
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /data/services/gatekeeper/conf:/etc/nginx/conf.d:rw
    networks:
      - proxy-tier
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    environment:
      TZ: "Europe/Stockholm"
    depends_on:
      - nginx
      - nginx-gen
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/services/gatekeeper/vhost:/etc/nginx/vhost.d:rw
      - /data/services/gatekeeper/certs:/etc/nginx/certs:rw
    environment:
      - "NGINX_DOCKER_GEN_CONTAINER=nginx-gen"

networks:
  proxy-tier:
    external:
      name: "nginx-proxy"
```

Then for each "subdomain" create a separate docker-compose file like this (here I'm using a simple nginx static webserver as an example, but as long as you provide the correct ports, you can add any service here):

```yaml
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=subdomain.mydomain.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=subdomain.mydomain.com
      - LETSENCRYPT_EMAIL=<email>
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: "nginx-proxy"
```
